# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/models/concept_affinities.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import concepts_pb2 as com_dot_baboea_dot_models_dot_concepts__pb2
from com.baboea.models import culinary_groups_pb2 as com_dot_baboea_dot_models_dot_culinary__groups__pb2
from com.baboea.models import recipes_pb2 as com_dot_baboea_dot_models_dot_recipes__pb2
from com.baboea.models import localized_pb2 as com_dot_baboea_dot_models_dot_localized__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*com/baboea/models/concept_affinities.proto\x12\x11\x63om.baboea.models\x1a com/baboea/models/concepts.proto\x1a\'com/baboea/models/culinary_groups.proto\x1a\x1f\x63om/baboea/models/recipes.proto\x1a!com/baboea/models/localized.proto\"\x89\x02\n\x0f\x43onceptAffinity\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x04\x66rom\x18\x02 \x01(\x0b\x32\x1d.com.baboea.models.ConceptRef\x12)\n\x02to\x18\x03 \x01(\x0b\x32\x1d.com.baboea.models.ConceptRef\x12\x10\n\x08\x61\x66\x66inity\x18\x04 \x01(\x01\x12\x36\n\tgroupOfTo\x18\x05 \x01(\x0b\x32#.com.baboea.models.CulinaryGroupRef\x12;\n\x08\x63\x61tegory\x18\x06 \x01(\x0b\x32$.com.baboea.models.RecipeCategoryRefH\x00\x88\x01\x01\x42\x0b\n\t_category\"x\n\x12\x43onceptAffinityRef\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x04\x66rom\x18\x02 \x01(\x0b\x32\x1d.com.baboea.models.ConceptRef\x12)\n\x02to\x18\x03 \x01(\x0b\x32\x1d.com.baboea.models.ConceptRefb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.models.concept_affinities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONCEPTAFFINITY']._serialized_start=209
  _globals['_CONCEPTAFFINITY']._serialized_end=474
  _globals['_CONCEPTAFFINITYREF']._serialized_start=476
  _globals['_CONCEPTAFFINITYREF']._serialized_end=596
# @@protoc_insertion_point(module_scope)
