# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/models/days.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/models/days.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import meal_pb2 as com_dot_baboea_dot_models_dot_meal__pb2
from com.baboea.models import users_pb2 as com_dot_baboea_dot_models_dot_users__pb2
from com.baboea.models import dates_pb2 as com_dot_baboea_dot_models_dot_dates__pb2
from com.baboea.models import plugins_pb2 as com_dot_baboea_dot_models_dot_plugins__pb2
from com.baboea import concept_pb2 as com_dot_baboea_dot_concept__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63om/baboea/models/days.proto\x12\x11\x63om.baboea.models\x1a\x1c\x63om/baboea/models/meal.proto\x1a\x1d\x63om/baboea/models/users.proto\x1a\x1d\x63om/baboea/models/dates.proto\x1a\x1f\x63om/baboea/models/plugins.proto\x1a\x18\x63om/baboea/concept.proto\"\x94\x02\n\x0bMealPlanDay\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x05meals\x18\x02 \x03(\x0b\x32\x1a.com.baboea.models.MealRef\x12)\n\x05owner\x18\x03 \x01(\x0b\x32\x1a.com.baboea.models.UserRef\x12\x0c\n\x04name\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x34\n\x0e\x61ppliedPlugins\x18\x07 \x03(\x0b\x32\x1c.com.baboea.models.PluginRef\x12J\n\x13\x64\x65\x66\x61ultDayVariables\x18\x08 \x03(\x0b\x32-.com.baboea.models.InstantiatedPluginVariable\"*\n\x0eMealPlanDayRef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"{\n\x0bUserPlanDay\x12-\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1f.com.baboea.models.CalendarDate\x12=\n\x12\x64\x65siredDayTemplate\x18\x02 \x01(\x0b\x32!.com.baboea.models.MealPlanDayRefb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.models.days_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEALPLANDAY']._serialized_start=203
  _globals['_MEALPLANDAY']._serialized_end=479
  _globals['_MEALPLANDAYREF']._serialized_start=481
  _globals['_MEALPLANDAYREF']._serialized_end=523
  _globals['_USERPLANDAY']._serialized_start=525
  _globals['_USERPLANDAY']._serialized_end=648
# @@protoc_insertion_point(module_scope)
