# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/models/test.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import food_pb2 as com_dot_baboea_dot_models_dot_food__pb2
from com.baboea.models import concepts_pb2 as com_dot_baboea_dot_models_dot_concepts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63om/baboea/models/test.proto\x12\x11\x63om.baboea.models\x1a\x1c\x63om/baboea/models/food.proto\x1a com/baboea/models/concepts.proto\"\x9c\x01\n\x0c\x43onceptCache\x12=\n\x07\x63oncept\x18\x01 \x03(\x0b\x32,.com.baboea.models.ConceptCache.ConceptEntry\x1aM\n\x0c\x43onceptEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.com.baboea.models.ConceptRef:\x02\x38\x01\"\x8b\x01\n\x04Test\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08lastname\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\x12\x0e\n\x06hellos\x18\x06 \x03(\t\x12)\n\x05\x66oods\x18\x07 \x03(\x0b\x32\x1a.com.baboea.models.FoodRef\"#\n\x07TestRef\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x19\n\tTestQuery\x12\x0c\n\x04name\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.models.test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONCEPTCACHE_CONCEPTENTRY']._loaded_options = None
  _globals['_CONCEPTCACHE_CONCEPTENTRY']._serialized_options = b'8\001'
  _globals['_CONCEPTCACHE']._serialized_start=116
  _globals['_CONCEPTCACHE']._serialized_end=272
  _globals['_CONCEPTCACHE_CONCEPTENTRY']._serialized_start=195
  _globals['_CONCEPTCACHE_CONCEPTENTRY']._serialized_end=272
  _globals['_TEST']._serialized_start=275
  _globals['_TEST']._serialized_end=414
  _globals['_TESTREF']._serialized_start=416
  _globals['_TESTREF']._serialized_end=451
  _globals['_TESTQUERY']._serialized_start=453
  _globals['_TESTQUERY']._serialized_end=478
# @@protoc_insertion_point(module_scope)
