# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/ai_recipe_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/ai_recipe_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import users_pb2 as com_dot_baboea_dot_models_dot_users__pb2
from com.baboea.models import template_recipe_data_pb2 as com_dot_baboea_dot_models_dot_template__recipe__data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+com/baboea/services/ai_recipe_service.proto\x12\x13\x63om.baboea.services\x1a\x1d\x63om/baboea/models/users.proto\x1a,com/baboea/models/template_recipe_data.proto\"Y\n\x19\x41iRecipeGenerationRequest\x12\x12\n\nrecipeName\x18\x01 \x01(\t\x12(\n\x04user\x18\x02 \x01(\x0b\x32\x1a.com.baboea.models.UserRef\"W\n\x1a\x41iRecipeGenerationResponse\x12\x39\n\x06recipe\x18\x01 \x01(\x0b\x32).com.baboea.models.ImprovedTemplateRecipe2\x8a\x01\n\x19\x41iRecipeGenerationService\x12m\n\x08Generate\x12..com.baboea.services.AiRecipeGenerationRequest\x1a/.com.baboea.services.AiRecipeGenerationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.ai_recipe_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AIRECIPEGENERATIONREQUEST']._serialized_start=145
  _globals['_AIRECIPEGENERATIONREQUEST']._serialized_end=234
  _globals['_AIRECIPEGENERATIONRESPONSE']._serialized_start=236
  _globals['_AIRECIPEGENERATIONRESPONSE']._serialized_end=323
  _globals['_AIRECIPEGENERATIONSERVICE']._serialized_start=326
  _globals['_AIRECIPEGENERATIONSERVICE']._serialized_end=464
# @@protoc_insertion_point(module_scope)
