# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/diet_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/diet_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import diet_pb2 as com_dot_baboea_dot_models_dot_diet__pb2
from com.baboea.models import users_pb2 as com_dot_baboea_dot_models_dot_users__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&com/baboea/services/diet_service.proto\x12\x13\x63om.baboea.services\x1a\x1c\x63om/baboea/models/diet.proto\x1a\x1d\x63om/baboea/models/users.proto\x1a\x1e\x63om/baboea/services/base.proto\"h\n\x16UserDietDefinitionList\x12\x37\n\x05items\x18\x01 \x03(\x0b\x32(.com.baboea.models.UserDietDefinitionRef\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"f\n\x1fUserDietDefinitionUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x37\n\x08newValue\x18\x02 \x01(\x0b\x32%.com.baboea.models.UserDietDefinition\"a\n\x17UserDietDefinitionQuery\x12)\n\x05owner\x18\x01 \x03(\x0b\x32\x1a.com.baboea.models.UserRef\x12\x0c\n\x04page\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x32\x86\x05\n\x0fUserDietService\x12\x65\n\x06Update\x12\x34.com.baboea.services.UserDietDefinitionUpdateRequest\x1a#.com.baboea.services.UpdateResponse\"\x00\x12P\n\x03\x41\x64\x64\x12%.com.baboea.models.UserDietDefinition\x1a .com.baboea.services.AddResponse\"\x00\x12O\n\x03Get\x12\x1f.com.baboea.services.GetRequest\x1a%.com.baboea.models.UserDietDefinition\"\x00\x12\x65\n\x06Search\x12,.com.baboea.services.UserDietDefinitionQuery\x1a+.com.baboea.services.UserDietDefinitionList\"\x00\x12[\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a+.com.baboea.services.UserDietDefinitionList\"\x00\x12M\n\x06\x42yUser\x12\x1a.com.baboea.models.UserRef\x1a%.com.baboea.models.UserDietDefinition\"\x00\x12V\n\x06Remove\x12%.com.baboea.models.UserDietDefinition\x1a#.com.baboea.services.RemoveResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.diet_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERDIETDEFINITIONLIST']._serialized_start=156
  _globals['_USERDIETDEFINITIONLIST']._serialized_end=260
  _globals['_USERDIETDEFINITIONUPDATEREQUEST']._serialized_start=262
  _globals['_USERDIETDEFINITIONUPDATEREQUEST']._serialized_end=364
  _globals['_USERDIETDEFINITIONQUERY']._serialized_start=366
  _globals['_USERDIETDEFINITIONQUERY']._serialized_end=463
  _globals['_USERDIETSERVICE']._serialized_start=466
  _globals['_USERDIETSERVICE']._serialized_end=1112
# @@protoc_insertion_point(module_scope)
