# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/entropic_value_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/entropic_value_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import recipe_entropy_pb2 as com_dot_baboea_dot_models_dot_recipe__entropy__pb2
from com.baboea.models import localized_pb2 as com_dot_baboea_dot_models_dot_localized__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0com/baboea/services/entropic_value_service.proto\x12\x13\x63om.baboea.services\x1a&com/baboea/models/recipe_entropy.proto\x1a!com/baboea/models/localized.proto\x1a\x1e\x63om/baboea/services/base.proto\"^\n\x11\x45ntropicValueList\x12\x32\n\x05items\x18\x01 \x03(\x0b\x32#.com.baboea.models.EntropicValueRef\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"\\\n\x1a\x45ntropicValueUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x32\n\x08newValue\x18\x02 \x01(\x0b\x32 .com.baboea.models.EntropicValue\"m\n\x12\x45ntropicValueQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12,\n\x06locale\x18\x04 \x01(\x0b\x32\x1c.com.baboea.models.LocaleRef2\x99\x04\n\x14\x45ntropicValueService\x12K\n\x03\x41\x64\x64\x12 .com.baboea.models.EntropicValue\x1a .com.baboea.services.AddResponse\"\x00\x12Q\n\x06Remove\x12 .com.baboea.models.EntropicValue\x1a#.com.baboea.services.RemoveResponse\"\x00\x12V\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a&.com.baboea.services.EntropicValueList\"\x00\x12[\n\x06Search\x12\'.com.baboea.services.EntropicValueQuery\x1a&.com.baboea.services.EntropicValueList\"\x00\x12J\n\x03Get\x12\x1f.com.baboea.services.GetRequest\x1a .com.baboea.models.EntropicValue\"\x00\x12`\n\x06Update\x12/.com.baboea.services.EntropicValueUpdateRequest\x1a#.com.baboea.services.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.entropic_value_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENTROPICVALUELIST']._serialized_start=180
  _globals['_ENTROPICVALUELIST']._serialized_end=274
  _globals['_ENTROPICVALUEUPDATEREQUEST']._serialized_start=276
  _globals['_ENTROPICVALUEUPDATEREQUEST']._serialized_end=368
  _globals['_ENTROPICVALUEQUERY']._serialized_start=370
  _globals['_ENTROPICVALUEQUERY']._serialized_end=479
  _globals['_ENTROPICVALUESERVICE']._serialized_start=482
  _globals['_ENTROPICVALUESERVICE']._serialized_end=1019
# @@protoc_insertion_point(module_scope)
