# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/meal_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/meal_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import meal_pb2 as com_dot_baboea_dot_models_dot_meal__pb2
from com.baboea.models import users_pb2 as com_dot_baboea_dot_models_dot_users__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&com/baboea/services/meal_service.proto\x12\x13\x63om.baboea.services\x1a\x1c\x63om/baboea/models/meal.proto\x1a\x1d\x63om/baboea/models/users.proto\x1a\x1e\x63om/baboea/services/base.proto\"L\n\x08MealList\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.com.baboea.models.MealRef\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"J\n\x11MealUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x08newValue\x18\x02 \x01(\x0b\x32\x17.com.baboea.models.Meal\"a\n\tMealQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12)\n\x05owner\x18\x04 \x01(\x0b\x32\x1a.com.baboea.models.UserRef2\xd1\x03\n\x0bMealService\x12\x42\n\x03\x41\x64\x64\x12\x17.com.baboea.models.Meal\x1a .com.baboea.services.AddResponse\"\x00\x12H\n\x06Remove\x12\x17.com.baboea.models.Meal\x1a#.com.baboea.services.RemoveResponse\"\x00\x12M\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a\x1d.com.baboea.services.MealList\"\x00\x12I\n\x06Search\x12\x1e.com.baboea.services.MealQuery\x1a\x1d.com.baboea.services.MealList\"\x00\x12\x41\n\x03Get\x12\x1f.com.baboea.services.GetRequest\x1a\x17.com.baboea.models.Meal\"\x00\x12W\n\x06Update\x12&.com.baboea.services.MealUpdateRequest\x1a#.com.baboea.services.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.meal_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEALLIST']._serialized_start=156
  _globals['_MEALLIST']._serialized_end=232
  _globals['_MEALUPDATEREQUEST']._serialized_start=234
  _globals['_MEALUPDATEREQUEST']._serialized_end=308
  _globals['_MEALQUERY']._serialized_start=310
  _globals['_MEALQUERY']._serialized_end=407
  _globals['_MEALSERVICE']._serialized_start=410
  _globals['_MEALSERVICE']._serialized_end=875
# @@protoc_insertion_point(module_scope)
