# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/meal_plan_plugin.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/meal_plan_plugin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import localized_pb2 as com_dot_baboea_dot_models_dot_localized__pb2
from com.baboea.models import days_pb2 as com_dot_baboea_dot_models_dot_days__pb2
from com.baboea.models import plugins_pb2 as com_dot_baboea_dot_models_dot_plugins__pb2
from com.baboea import generaterequest_pb2 as com_dot_baboea_dot_generaterequest__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*com/baboea/services/meal_plan_plugin.proto\x12\x11\x63om.baboea.models\x1a!com/baboea/models/localized.proto\x1a\x1c\x63om/baboea/models/days.proto\x1a\x1f\x63om/baboea/models/plugins.proto\x1a com/baboea/generaterequest.proto\"\x82\x01\n\x11MealPlanPluginDay\x12+\n\x03\x64\x61y\x18\x01 \x01(\x0b\x32\x1e.com.baboea.models.UserPlanDay\x12@\n\tvariables\x18\x02 \x03(\x0b\x32-.com.baboea.models.InstantiatedPluginVariable\"\x92\x01\n\x1eMealPlanPluginTransformRequest\x12<\n\x0fgenerateRequest\x18\x01 \x01(\x0b\x32#.com.baboea.MealPlanGenerateRequest\x12\x32\n\x04\x64\x61ys\x18\x02 \x03(\x0b\x32$.com.baboea.models.MealPlanPluginDay\"[\n\x1fMealPlanPluginTransformResponse\x12\x38\n\x0btransformed\x18\x01 \x01(\x0b\x32#.com.baboea.MealPlanGenerateRequest2\x86\x01\n\x0eMealPlanPlugin\x12t\n\tTransform\x12\x31.com.baboea.models.MealPlanPluginTransformRequest\x1a\x32.com.baboea.models.MealPlanPluginTransformResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.meal_plan_plugin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEALPLANPLUGINDAY']._serialized_start=198
  _globals['_MEALPLANPLUGINDAY']._serialized_end=328
  _globals['_MEALPLANPLUGINTRANSFORMREQUEST']._serialized_start=331
  _globals['_MEALPLANPLUGINTRANSFORMREQUEST']._serialized_end=477
  _globals['_MEALPLANPLUGINTRANSFORMRESPONSE']._serialized_start=479
  _globals['_MEALPLANPLUGINTRANSFORMRESPONSE']._serialized_end=570
  _globals['_MEALPLANPLUGIN']._serialized_start=573
  _globals['_MEALPLANPLUGIN']._serialized_end=707
# @@protoc_insertion_point(module_scope)
