# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/plugin_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/plugin_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import plugins_pb2 as com_dot_baboea_dot_models_dot_plugins__pb2
from com.baboea.models import localized_pb2 as com_dot_baboea_dot_models_dot_localized__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(com/baboea/services/plugin_service.proto\x12\x13\x63om.baboea.services\x1a\x1f\x63om/baboea/models/plugins.proto\x1a!com/baboea/models/localized.proto\x1a\x1e\x63om/baboea/services/base.proto\"P\n\nPluginList\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.com.baboea.models.PluginRef\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"N\n\x13PluginUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12+\n\x08newValue\x18\x02 \x01(\x0b\x32\x19.com.baboea.models.Plugin\"f\n\x0bPluginQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12,\n\x06locale\x18\x04 \x01(\x0b\x32\x1c.com.baboea.models.LocaleRef2\xe1\x03\n\rPluginService\x12\x44\n\x03\x41\x64\x64\x12\x19.com.baboea.models.Plugin\x1a .com.baboea.services.AddResponse\"\x00\x12J\n\x06Remove\x12\x19.com.baboea.models.Plugin\x1a#.com.baboea.services.RemoveResponse\"\x00\x12O\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a\x1f.com.baboea.services.PluginList\"\x00\x12M\n\x06Search\x12 .com.baboea.services.PluginQuery\x1a\x1f.com.baboea.services.PluginList\"\x00\x12\x43\n\x03Get\x12\x1f.com.baboea.services.GetRequest\x1a\x19.com.baboea.models.Plugin\"\x00\x12Y\n\x06Update\x12(.com.baboea.services.PluginUpdateRequest\x1a#.com.baboea.services.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.plugin_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLUGINLIST']._serialized_start=165
  _globals['_PLUGINLIST']._serialized_end=245
  _globals['_PLUGINUPDATEREQUEST']._serialized_start=247
  _globals['_PLUGINUPDATEREQUEST']._serialized_end=325
  _globals['_PLUGINQUERY']._serialized_start=327
  _globals['_PLUGINQUERY']._serialized_end=429
  _globals['_PLUGINSERVICE']._serialized_start=432
  _globals['_PLUGINSERVICE']._serialized_end=913
# @@protoc_insertion_point(module_scope)
