# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/scrape_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/scrape_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import scraping_pb2 as com_dot_baboea_dot_models_dot_scraping__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2
from com.baboea.models import recipes_pb2 as com_dot_baboea_dot_models_dot_recipes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(com/baboea/services/scrape_service.proto\x12\x13\x63om.baboea.services\x1a com/baboea/models/scraping.proto\x1a\x1e\x63om/baboea/services/base.proto\x1a\x1f\x63om/baboea/models/recipes.proto\"V\n\x0b\x44omainsList\x12\x30\n\x07\x64omains\x18\x01 \x03(\x0b\x32\x1f.com.baboea.models.ScrapeDomain\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"#\n\x0fGetPagesRequest\x12\x10\n\x08\x64omainId\x18\x01 \x01(\t\"V\n\x12UpdatePagesRequest\x12\x10\n\x08\x64omainId\x18\x01 \x01(\t\x12.\n\x04urls\x18\x02 \x03(\x0b\x32 .com.baboea.models.UrlScrapeNode\"Y\n\x10GetPagesResponse\x12.\n\x04urls\x18\x01 \x03(\x0b\x32 .com.baboea.models.UrlScrapeNode\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"J\n\rScrapedObject\x12\x31\n\x06recipe\x18\x01 \x01(\x0b\x32\x1f.com.baboea.models.RemoteRecipeH\x00\x42\x06\n\x04\x64\x61ta\"\x8c\x01\n\x0bScrapedPage\x12\x0e\n\x06\x64omain\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\x32\n\x06nugget\x18\x03 \x01(\x0b\x32\".com.baboea.services.ScrapedObject\x12\x1a\n\rlocaleIso6391\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x10\n\x0e_localeIso63912\x9b\x04\n\x11ScrapeDataService\x12P\n\tAddDomain\x12\x1f.com.baboea.models.ScrapeDomain\x1a .com.baboea.services.AddResponse\"\x00\x12V\n\x0cRemoveDomain\x12\x1f.com.baboea.models.ScrapeDomain\x1a#.com.baboea.services.RemoveResponse\"\x00\x12V\n\x0cUpdateDomain\x12\x1f.com.baboea.models.ScrapeDomain\x1a#.com.baboea.services.UpdateResponse\"\x00\x12P\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a .com.baboea.services.DomainsList\"\x00\x12Z\n\x0bGetAllPages\x12\".com.baboea.services.GetAllRequest\x1a%.com.baboea.services.GetPagesResponse\"\x00\x12V\n\x0e\x41\x64\x64ScrapedPage\x12 .com.baboea.services.ScrapedPage\x1a .com.baboea.services.AddResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.scrape_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOMAINSLIST']._serialized_start=164
  _globals['_DOMAINSLIST']._serialized_end=250
  _globals['_GETPAGESREQUEST']._serialized_start=252
  _globals['_GETPAGESREQUEST']._serialized_end=287
  _globals['_UPDATEPAGESREQUEST']._serialized_start=289
  _globals['_UPDATEPAGESREQUEST']._serialized_end=375
  _globals['_GETPAGESRESPONSE']._serialized_start=377
  _globals['_GETPAGESRESPONSE']._serialized_end=466
  _globals['_SCRAPEDOBJECT']._serialized_start=468
  _globals['_SCRAPEDOBJECT']._serialized_end=542
  _globals['_SCRAPEDPAGE']._serialized_start=545
  _globals['_SCRAPEDPAGE']._serialized_end=685
  _globals['_SCRAPEDATASERVICE']._serialized_start=688
  _globals['_SCRAPEDATASERVICE']._serialized_end=1227
# @@protoc_insertion_point(module_scope)
