# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from com.baboea.services import template_recipe_service_pb2 as com_dot_baboea_dot_services_dot_template__recipe__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in com/baboea/services/smart_template_recipe_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartTemplateRecipeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSmart = channel.unary_unary(
                '/com.baboea.services.SmartTemplateRecipeService/GetSmart',
                request_serializer=com_dot_baboea_dot_services_dot_template__recipe__service__pb2.SmartTemplateRecipeQuery.SerializeToString,
                response_deserializer=com_dot_baboea_dot_services_dot_template__recipe__service__pb2.SmartTemplateRecipeResponse.FromString,
                _registered_method=True)


class SmartTemplateRecipeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSmart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartTemplateRecipeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSmart': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSmart,
                    request_deserializer=com_dot_baboea_dot_services_dot_template__recipe__service__pb2.SmartTemplateRecipeQuery.FromString,
                    response_serializer=com_dot_baboea_dot_services_dot_template__recipe__service__pb2.SmartTemplateRecipeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.baboea.services.SmartTemplateRecipeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.baboea.services.SmartTemplateRecipeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartTemplateRecipeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSmart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.baboea.services.SmartTemplateRecipeService/GetSmart',
            com_dot_baboea_dot_services_dot_template__recipe__service__pb2.SmartTemplateRecipeQuery.SerializeToString,
            com_dot_baboea_dot_services_dot_template__recipe__service__pb2.SmartTemplateRecipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
