# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/smart_template_recipe_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/smart_template_recipe_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.services import template_recipe_service_pb2 as com_dot_baboea_dot_services_dot_template__recipe__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7com/baboea/services/smart_template_recipe_service.proto\x12\x13\x63om.baboea.services\x1a\x31\x63om/baboea/services/template_recipe_service.proto2\x8b\x01\n\x1aSmartTemplateRecipeService\x12m\n\x08GetSmart\x12-.com.baboea.services.SmartTemplateRecipeQuery\x1a\x30.com.baboea.services.SmartTemplateRecipeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.smart_template_recipe_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SMARTTEMPLATERECIPESERVICE']._serialized_start=132
  _globals['_SMARTTEMPLATERECIPESERVICE']._serialized_end=271
# @@protoc_insertion_point(module_scope)
