# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/services/template_recipe_property_bound_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import template_recipe_data_pb2 as com_dot_baboea_dot_models_dot_template__recipe__data__pb2
from com.baboea.models import property_pb2 as com_dot_baboea_dot_models_dot_property__pb2
from com.baboea.models import food_pb2 as com_dot_baboea_dot_models_dot_food__pb2
from com.baboea.models import concepts_pb2 as com_dot_baboea_dot_models_dot_concepts__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@com/baboea/services/template_recipe_property_bound_service.proto\x12\x13\x63om.baboea.services\x1a,com/baboea/models/template_recipe_data.proto\x1a com/baboea/models/property.proto\x1a\x1c\x63om/baboea/models/food.proto\x1a com/baboea/models/concepts.proto\"k\n\x0e\x43onceptOptions\x12.\n\x07\x63oncept\x18\x01 \x01(\x0b\x32\x1d.com.baboea.models.ConceptRef\x12)\n\x05\x66oods\x18\x02 \x03(\x0b\x32\x1a.com.baboea.models.FoodRef\"p\n\x0e\x46oodProperties\x12(\n\x04\x66ood\x18\x01 \x01(\x0b\x32\x1a.com.baboea.models.FoodRef\x12\x34\n\nproperties\x18\x02 \x03(\x0b\x32 .com.baboea.models.PropertyValue\"\x99\x01\n!ComputeTemplateRecipeBoundRequest\x12\x39\n\x06recipe\x18\x01 \x01(\x0b\x32).com.baboea.models.ImprovedTemplateRecipe\x12\x39\n\x11\x64\x65siredProperties\x18\x02 \x03(\x0b\x32\x1e.com.baboea.models.PropertyRef\"o\n\rPropertyBound\x12\x30\n\x08property\x18\x01 \x01(\x0b\x32\x1e.com.baboea.models.PropertyRef\x12\x15\n\rminPer100Kcal\x18\x02 \x01(\x01\x12\x15\n\rmaxPer100Kcal\x18\x03 \x01(\x01\"z\n\"ComputeTemplateRecipeBoundResponse\x12\x32\n\x06\x62ounds\x18\x01 \x03(\x0b\x32\".com.baboea.services.PropertyBound\x12\x0f\n\x07minKcal\x18\x02 \x01(\x01\x12\x0f\n\x07maxKcal\x18\x03 \x01(\x01\x32\xa1\x01\n\x1aTemplateRecipeBoundService\x12\x82\x01\n\rComputeBounds\x12\x36.com.baboea.services.ComputeTemplateRecipeBoundRequest\x1a\x37.com.baboea.services.ComputeTemplateRecipeBoundResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.template_recipe_property_bound_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONCEPTOPTIONS']._serialized_start=233
  _globals['_CONCEPTOPTIONS']._serialized_end=340
  _globals['_FOODPROPERTIES']._serialized_start=342
  _globals['_FOODPROPERTIES']._serialized_end=454
  _globals['_COMPUTETEMPLATERECIPEBOUNDREQUEST']._serialized_start=457
  _globals['_COMPUTETEMPLATERECIPEBOUNDREQUEST']._serialized_end=610
  _globals['_PROPERTYBOUND']._serialized_start=612
  _globals['_PROPERTYBOUND']._serialized_end=723
  _globals['_COMPUTETEMPLATERECIPEBOUNDRESPONSE']._serialized_start=725
  _globals['_COMPUTETEMPLATERECIPEBOUNDRESPONSE']._serialized_end=847
  _globals['_TEMPLATERECIPEBOUNDSERVICE']._serialized_start=850
  _globals['_TEMPLATERECIPEBOUNDSERVICE']._serialized_end=1011
# @@protoc_insertion_point(module_scope)
