# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/services/test_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/services/test_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import test_pb2 as com_dot_baboea_dot_models_dot_test__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&com/baboea/services/test_service.proto\x12\x13\x63om.baboea.services\x1a\x1c\x63om/baboea/models/test.proto\x1a\x1e\x63om/baboea/services/base.proto\"L\n\x08TestList\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.com.baboea.models.TestRef\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"J\n\x11TestUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x08newValue\x18\x02 \x01(\x0b\x32\x17.com.baboea.models.Test2\x91\x03\n\x0bTestService\x12\x42\n\x03\x41\x64\x64\x12\x17.com.baboea.models.Test\x1a .com.baboea.services.AddResponse\"\x00\x12S\n\x06Remove\x12\".com.baboea.services.RemoveRequest\x1a#.com.baboea.services.RemoveResponse\"\x00\x12M\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a\x1d.com.baboea.services.TestList\"\x00\x12\x41\n\x03Get\x12\x1f.com.baboea.services.GetRequest\x1a\x17.com.baboea.models.Test\"\x00\x12W\n\x06Update\x12&.com.baboea.services.TestUpdateRequest\x1a#.com.baboea.services.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.test_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TESTLIST']._serialized_start=125
  _globals['_TESTLIST']._serialized_end=201
  _globals['_TESTUPDATEREQUEST']._serialized_start=203
  _globals['_TESTUPDATEREQUEST']._serialized_end=277
  _globals['_TESTSERVICE']._serialized_start=280
  _globals['_TESTSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
