# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/services/unit_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import food_units_pb2 as com_dot_baboea_dot_models_dot_food__units__pb2
from com.baboea.models import localized_pb2 as com_dot_baboea_dot_models_dot_localized__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&com/baboea/services/unit_service.proto\x12\x13\x63om.baboea.services\x1a\"com/baboea/models/food_units.proto\x1a!com/baboea/models/localized.proto\x1a\x1e\x63om/baboea/services/base.proto\"T\n\x0c\x46oodUnitList\x12-\n\x05items\x18\x01 \x03(\x0b\x32\x1e.com.baboea.models.FoodUnitRef\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"R\n\x15\x46oodUnitUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12-\n\x08newValue\x18\x02 \x01(\x0b\x32\x1b.com.baboea.models.FoodUnit\"h\n\rFoodUnitQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\x12,\n\x06locale\x18\x04 \x01(\x0b\x32\x1c.com.baboea.models.LocaleRef2\xd5\x04\n\x0f\x46oodUnitService\x12\x46\n\x03\x41\x64\x64\x12\x1b.com.baboea.models.FoodUnit\x1a .com.baboea.services.AddResponse\"\x00\x12\x62\n\x10\x42yHandleOrCreate\x12,.com.baboea.services.FindSingleHandleRequest\x1a\x1e.com.baboea.models.FoodUnitRef\"\x00\x12L\n\x06Remove\x12\x1b.com.baboea.models.FoodUnit\x1a#.com.baboea.services.RemoveResponse\"\x00\x12Q\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a!.com.baboea.services.FoodUnitList\"\x00\x12Q\n\x06Search\x12\".com.baboea.services.FoodUnitQuery\x1a!.com.baboea.services.FoodUnitList\"\x00\x12\x45\n\x03Get\x12\x1f.com.baboea.services.GetRequest\x1a\x1b.com.baboea.models.FoodUnit\"\x00\x12[\n\x06Update\x12*.com.baboea.services.FoodUnitUpdateRequest\x1a#.com.baboea.services.UpdateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.unit_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FOODUNITLIST']._serialized_start=166
  _globals['_FOODUNITLIST']._serialized_end=250
  _globals['_FOODUNITUPDATEREQUEST']._serialized_start=252
  _globals['_FOODUNITUPDATEREQUEST']._serialized_end=334
  _globals['_FOODUNITQUERY']._serialized_start=336
  _globals['_FOODUNITQUERY']._serialized_end=440
  _globals['_FOODUNITSERVICE']._serialized_start=443
  _globals['_FOODUNITSERVICE']._serialized_end=1040
# @@protoc_insertion_point(module_scope)
