# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/services/user_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import users_pb2 as com_dot_baboea_dot_models_dot_users__pb2
from com.baboea.models import localized_pb2 as com_dot_baboea_dot_models_dot_localized__pb2
from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&com/baboea/services/user_service.proto\x12\x13\x63om.baboea.services\x1a\x1d\x63om/baboea/models/users.proto\x1a!com/baboea/models/localized.proto\x1a\x1e\x63om/baboea/services/base.proto\"L\n\x08UserList\x12)\n\x05items\x18\x01 \x03(\x0b\x32\x1a.com.baboea.models.UserRef\x12\x15\n\rnextPageToken\x18\x02 \x01(\t\"J\n\x11UserUpdateRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12)\n\x08newValue\x18\x02 \x01(\x0b\x32\x17.com.baboea.models.User\"6\n\tUserQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\t\x12\r\n\x05limit\x18\x03 \x01(\x05\")\n\x15\x46indByRemoteIdRequest\x12\x10\n\x08remoteId\x18\x01 \x01(\t\"d\n\x16\x46indByRemoteIdResponse\x12*\n\x04user\x18\x01 \x01(\x0b\x32\x1a.com.baboea.models.UserRefH\x00\x12\x14\n\nfirstLogin\x18\x02 \x01(\x08H\x00\x42\x08\n\x06result2\x97\x05\n\x0bUserService\x12\x42\n\x03\x41\x64\x64\x12\x17.com.baboea.models.User\x1a .com.baboea.services.AddResponse\"\x00\x12H\n\x06Remove\x12\x17.com.baboea.models.User\x1a#.com.baboea.services.RemoveResponse\"\x00\x12M\n\x06GetAll\x12\".com.baboea.services.GetAllRequest\x1a\x1d.com.baboea.services.UserList\"\x00\x12I\n\x06Search\x12\x1e.com.baboea.services.UserQuery\x1a\x1d.com.baboea.services.UserList\"\x00\x12\x41\n\x03Get\x12\x1f.com.baboea.services.GetRequest\x1a\x17.com.baboea.models.User\"\x00\x12W\n\x06Update\x12&.com.baboea.services.UserUpdateRequest\x1a#.com.baboea.services.UpdateResponse\"\x00\x12k\n\x0e\x46indByRemoteId\x12*.com.baboea.services.FindByRemoteIdRequest\x1a+.com.baboea.services.FindByRemoteIdResponse\"\x00\x12W\n\x0c\x46indByHandle\x12,.com.baboea.services.FindSingleHandleRequest\x1a\x17.com.baboea.models.User\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.services.user_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERLIST']._serialized_start=161
  _globals['_USERLIST']._serialized_end=237
  _globals['_USERUPDATEREQUEST']._serialized_start=239
  _globals['_USERUPDATEREQUEST']._serialized_end=313
  _globals['_USERQUERY']._serialized_start=315
  _globals['_USERQUERY']._serialized_end=369
  _globals['_FINDBYREMOTEIDREQUEST']._serialized_start=371
  _globals['_FINDBYREMOTEIDREQUEST']._serialized_end=412
  _globals['_FINDBYREMOTEIDRESPONSE']._serialized_start=414
  _globals['_FINDBYREMOTEIDRESPONSE']._serialized_end=514
  _globals['_USERSERVICE']._serialized_start=517
  _globals['_USERSERVICE']._serialized_end=1180
# @@protoc_insertion_point(module_scope)
