# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from com.baboea.services import base_pb2 as com_dot_baboea_dot_services_dot_base__pb2
from com.baboea.services import user_feedback_service_pb2 as com_dot_baboea_dot_services_dot_user__feedback__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in com/baboea/services/user_feedback_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserFeedbackServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NeverSuggestAgain = channel.unary_unary(
                '/com.baboea.services.UserFeedbackService/NeverSuggestAgain',
                request_serializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.NeverSuggestAgainRequest.SerializeToString,
                response_deserializer=com_dot_baboea_dot_services_dot_base__pb2.OperationResponse.FromString,
                _registered_method=True)
        self.FindConceptPath = channel.unary_unary(
                '/com.baboea.services.UserFeedbackService/FindConceptPath',
                request_serializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathRequest.SerializeToString,
                response_deserializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathResponse.FromString,
                _registered_method=True)
        self.GiveRecipeFeedback = channel.unary_unary(
                '/com.baboea.services.UserFeedbackService/GiveRecipeFeedback',
                request_serializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.GiveRecipeFeedbackRequest.SerializeToString,
                response_deserializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathResponse.FromString,
                _registered_method=True)


class UserFeedbackServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NeverSuggestAgain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindConceptPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GiveRecipeFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserFeedbackServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NeverSuggestAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.NeverSuggestAgain,
                    request_deserializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.NeverSuggestAgainRequest.FromString,
                    response_serializer=com_dot_baboea_dot_services_dot_base__pb2.OperationResponse.SerializeToString,
            ),
            'FindConceptPath': grpc.unary_unary_rpc_method_handler(
                    servicer.FindConceptPath,
                    request_deserializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathRequest.FromString,
                    response_serializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathResponse.SerializeToString,
            ),
            'GiveRecipeFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.GiveRecipeFeedback,
                    request_deserializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.GiveRecipeFeedbackRequest.FromString,
                    response_serializer=com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.baboea.services.UserFeedbackService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.baboea.services.UserFeedbackService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserFeedbackService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NeverSuggestAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.baboea.services.UserFeedbackService/NeverSuggestAgain',
            com_dot_baboea_dot_services_dot_user__feedback__service__pb2.NeverSuggestAgainRequest.SerializeToString,
            com_dot_baboea_dot_services_dot_base__pb2.OperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindConceptPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.baboea.services.UserFeedbackService/FindConceptPath',
            com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathRequest.SerializeToString,
            com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GiveRecipeFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.baboea.services.UserFeedbackService/GiveRecipeFeedback',
            com_dot_baboea_dot_services_dot_user__feedback__service__pb2.GiveRecipeFeedbackRequest.SerializeToString,
            com_dot_baboea_dot_services_dot_user__feedback__service__pb2.FindConceptPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
