# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from com.baboea import generaterequest_pb2 as com_dot_baboea_dot_generaterequest__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in com/baboea/services/user_plan_resolve_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerateResolverStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Resolve = channel.unary_unary(
                '/com.baboea.services.GenerateResolver/Resolve',
                request_serializer=com_dot_baboea_dot_generaterequest__pb2.UserPlanInput.SerializeToString,
                response_deserializer=com_dot_baboea_dot_generaterequest__pb2.MealPlanGenerateRequest.FromString,
                _registered_method=True)


class GenerateResolverServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerateResolverServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.Resolve,
                    request_deserializer=com_dot_baboea_dot_generaterequest__pb2.UserPlanInput.FromString,
                    response_serializer=com_dot_baboea_dot_generaterequest__pb2.MealPlanGenerateRequest.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.baboea.services.GenerateResolver', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.baboea.services.GenerateResolver', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerateResolver(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.baboea.services.GenerateResolver/Resolve',
            com_dot_baboea_dot_generaterequest__pb2.UserPlanInput.SerializeToString,
            com_dot_baboea_dot_generaterequest__pb2.MealPlanGenerateRequest.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
