# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/features.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import recipes_pb2 as com_dot_baboea_dot_models_dot_recipes__pb2
from com.baboea.models import meal_pb2 as com_dot_baboea_dot_models_dot_meal__pb2
from com.baboea.models import property_pb2 as com_dot_baboea_dot_models_dot_property__pb2
from com.baboea import foodgroup_pb2 as com_dot_baboea_dot_foodgroup__pb2
from com.baboea import concept_pb2 as com_dot_baboea_dot_concept__pb2
from com.baboea.models import food_pb2 as com_dot_baboea_dot_models_dot_food__pb2
from com.baboea import selector_pb2 as com_dot_baboea_dot_selector__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63om/baboea/features.proto\x12\ncom.baboea\x1a\x1f\x63om/baboea/models/recipes.proto\x1a\x1c\x63om/baboea/models/meal.proto\x1a com/baboea/models/property.proto\x1a\x1a\x63om/baboea/foodgroup.proto\x1a\x18\x63om/baboea/concept.proto\x1a\x1c\x63om/baboea/models/food.proto\x1a\x19\x63om/baboea/selector.proto\"O\n\x0f\x44istributeFoods\x12\x0c\n\x04\x66ood\x18\x01 \x03(\t\x12.\n\x05meals\x18\x02 \x03(\x0b\x32\x1f.com.baboea.FoodGroupIdentifier\"G\n\x08MealSize\x12-\n\x04meal\x18\x01 \x01(\x0b\x32\x1f.com.baboea.FoodGroupIdentifier\x12\x0c\n\x04size\x18\x02 \x01(\x01\"{\n\x12\x44istributeNutrient\x12\x30\n\x08property\x18\x01 \x01(\x0b\x32\x1e.com.baboea.models.PropertyRef\x12#\n\x05sizes\x18\x02 \x03(\x0b\x32\x14.com.baboea.MealSize\x12\x0e\n\x06margin\x18\x03 \x01(\x01\"\xea\x01\n\x10\x41\x64\x64MealComponent\x12-\n\x04meal\x18\x01 \x01(\x0b\x32\x1f.com.baboea.FoodGroupIdentifier\x12\'\n\x05sides\x18\x02 \x01(\x0b\x32\x16.com.baboea.SideDishesH\x00\x12:\n\x06recipe\x18\x03 \x01(\x0b\x32(.com.baboea.models.ParsedRemoteRecipeRefH\x00\x12:\n\x05smart\x18\x04 \x01(\x0b\x32).com.baboea.models.SmartRecipePreferencesH\x00\x42\x06\n\x04\x64ish\"=\n\nSideDishes\x12/\n\x08\x63oncepts\x18\x05 \x03(\x0b\x32\x1d.com.baboea.BoolConceptValuesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.features_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DISTRIBUTEFOODS']._serialized_start=249
  _globals['_DISTRIBUTEFOODS']._serialized_end=328
  _globals['_MEALSIZE']._serialized_start=330
  _globals['_MEALSIZE']._serialized_end=401
  _globals['_DISTRIBUTENUTRIENT']._serialized_start=403
  _globals['_DISTRIBUTENUTRIENT']._serialized_end=526
  _globals['_ADDMEALCOMPONENT']._serialized_start=529
  _globals['_ADDMEALCOMPONENT']._serialized_end=763
  _globals['_SIDEDISHES']._serialized_start=765
  _globals['_SIDEDISHES']._serialized_end=826
# @@protoc_insertion_point(module_scope)
