# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/foodgroup.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea.models import days_pb2 as com_dot_baboea_dot_models_dot_days__pb2
from com.baboea.models import meal_components_pb2 as com_dot_baboea_dot_models_dot_meal__components__pb2
from com.baboea.models import meal_pb2 as com_dot_baboea_dot_models_dot_meal__pb2
from com.baboea.models import recipes_pb2 as com_dot_baboea_dot_models_dot_recipes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63om/baboea/foodgroup.proto\x12\ncom.baboea\x1a\x1c\x63om/baboea/models/days.proto\x1a\'com/baboea/models/meal_components.proto\x1a\x1c\x63om/baboea/models/meal.proto\x1a\x1f\x63om/baboea/models/recipes.proto\"\x06\n\x04Root\"\xf4\x01\n\rFoodGroupNode\x12\x30\n\x03\x64\x61y\x18\x01 \x01(\x0b\x32!.com.baboea.models.MealPlanDayRefH\x00\x12*\n\x04meal\x18\x02 \x01(\x0b\x32\x1a.com.baboea.models.MealRefH\x00\x12<\n\rmealComponent\x18\x03 \x01(\x0b\x32#.com.baboea.models.MealComponentRefH\x00\x12:\n\x06recipe\x18\x04 \x01(\x0b\x32(.com.baboea.models.ParsedRemoteRecipeRefH\x00\x42\x0b\n\tcomponent\">\n\x13\x46oodGroupIdentifier\x12\'\n\x04path\x18\x01 \x03(\x0b\x32\x19.com.baboea.FoodGroupNode\"\x18\n\nRecipeNode\x12\n\n\x02id\x18\x01 \x01(\t*,\n\x12MealComponentGroup\x12\t\n\x05SIDES\x10\x00\x12\x0b\n\x07RECIPES\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.foodgroup_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEALCOMPONENTGROUP']._serialized_start=521
  _globals['_MEALCOMPONENTGROUP']._serialized_end=565
  _globals['_ROOT']._serialized_start=176
  _globals['_ROOT']._serialized_end=182
  _globals['_FOODGROUPNODE']._serialized_start=185
  _globals['_FOODGROUPNODE']._serialized_end=429
  _globals['_FOODGROUPIDENTIFIER']._serialized_start=431
  _globals['_FOODGROUPIDENTIFIER']._serialized_end=493
  _globals['_RECIPENODE']._serialized_start=495
  _globals['_RECIPENODE']._serialized_end=519
# @@protoc_insertion_point(module_scope)
