# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/baboea/generateservice.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'com/baboea/generateservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from com.baboea import generaterequest_pb2 as com_dot_baboea_dot_generaterequest__pb2
from com.baboea import foodgroup_pb2 as com_dot_baboea_dot_foodgroup__pb2
from com.baboea import selector_pb2 as com_dot_baboea_dot_selector__pb2
from com.baboea.models import food_pb2 as com_dot_baboea_dot_models_dot_food__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n com/baboea/generateservice.proto\x12\ncom.baboea\x1a com/baboea/generaterequest.proto\x1a\x1a\x63om/baboea/foodgroup.proto\x1a\x19\x63om/baboea/selector.proto\x1a\x1c\x63om/baboea/models/food.proto\"=\n\x11GeneratedFoodList\x12(\n\x05\x66oods\x18\x02 \x03(\x0b\x32\x19.com.baboea.GeneratedFood\"I\n\rGeneratedFood\x12(\n\x04\x66ood\x18\x01 \x01(\x0b\x32\x1a.com.baboea.models.FoodRef\x12\x0e\n\x06weight\x18\x03 \x01(\x01\"Q\n\x18PropertyValueInformation\x12&\n\x08property\x18\x01 \x01(\x0b\x32\x14.com.baboea.Property\x12\r\n\x05value\x18\x02 \x01(\x01\"X\n\x1cPropertyValueInformationList\x12\x38\n\nproperties\x18\x01 \x03(\x0b\x32$.com.baboea.PropertyValueInformation\"*\n\x12RecipeInstructions\x12\x14\n\x0cinstructions\x18\x01 \x01(\t\"\xcc\x01\n\x13GenerateInformation\x12.\n\x05\x66oods\x18\x01 \x01(\x0b\x32\x1d.com.baboea.GeneratedFoodListH\x00\x12>\n\nproperties\x18\x02 \x01(\x0b\x32(.com.baboea.PropertyValueInformationListH\x00\x12\x36\n\x0cinstructions\x18\x03 \x01(\x0b\x32\x1e.com.baboea.RecipeInstructionsH\x00\x42\r\n\x0binformation\"\xa1\x01\n\x11GeneratedFoodTree\x12/\n\x08\x63hildren\x18\x01 \x03(\x0b\x32\x1d.com.baboea.GeneratedFoodTree\x12\x32\n\tinfoNodes\x18\x02 \x03(\x0b\x32\x1f.com.baboea.GenerateInformation\x12\'\n\x04node\x18\x04 \x01(\x0b\x32\x19.com.baboea.FoodGroupNode\">\n\x0fGenerateSuccess\x12+\n\x04tree\x18\x02 \x03(\x0b\x32\x1d.com.baboea.GeneratedFoodTree\"\"\n\x0fGenerateFailure\x12\x0f\n\x07message\x18\x01 \x01(\t\"y\n\x10GenerateResponse\x12,\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x1b.com.baboea.GenerateFailureH\x00\x12-\n\x04plan\x18\x02 \x01(\x0b\x32\x1d.com.baboea.GeneratedMealPlanH\x00\x42\x08\n\x06status2X\n\x0fGenerateService\x12\x45\n\x08Generate\x12\x19.com.baboea.UserPlanInput\x1a\x1c.com.baboea.GenerateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.generateservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEDFOODLIST']._serialized_start=167
  _globals['_GENERATEDFOODLIST']._serialized_end=228
  _globals['_GENERATEDFOOD']._serialized_start=230
  _globals['_GENERATEDFOOD']._serialized_end=303
  _globals['_PROPERTYVALUEINFORMATION']._serialized_start=305
  _globals['_PROPERTYVALUEINFORMATION']._serialized_end=386
  _globals['_PROPERTYVALUEINFORMATIONLIST']._serialized_start=388
  _globals['_PROPERTYVALUEINFORMATIONLIST']._serialized_end=476
  _globals['_RECIPEINSTRUCTIONS']._serialized_start=478
  _globals['_RECIPEINSTRUCTIONS']._serialized_end=520
  _globals['_GENERATEINFORMATION']._serialized_start=523
  _globals['_GENERATEINFORMATION']._serialized_end=727
  _globals['_GENERATEDFOODTREE']._serialized_start=730
  _globals['_GENERATEDFOODTREE']._serialized_end=891
  _globals['_GENERATESUCCESS']._serialized_start=893
  _globals['_GENERATESUCCESS']._serialized_end=955
  _globals['_GENERATEFAILURE']._serialized_start=957
  _globals['_GENERATEFAILURE']._serialized_end=991
  _globals['_GENERATERESPONSE']._serialized_start=993
  _globals['_GENERATERESPONSE']._serialized_end=1114
  _globals['_GENERATESERVICE']._serialized_start=1116
  _globals['_GENERATESERVICE']._serialized_end=1204
# @@protoc_insertion_point(module_scope)
