# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/groep.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63om/baboea/groep.proto\x12\ncom.baboea\"#\n\x06\x42\x61\x62oea\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"L\n\x08SuperBab\x12\x1f\n\x03\x62\x61\x62\x18\x01 \x01(\x0b\x32\x12.com.baboea.Baboea\x12\x0c\n\x04\x66ire\x18\x02 \x01(\x05\x12\x11\n\tbabstatus\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.groep_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BABOEA']._serialized_start=38
  _globals['_BABOEA']._serialized_end=73
  _globals['_SUPERBAB']._serialized_start=75
  _globals['_SUPERBAB']._serialized_end=151
# @@protoc_insertion_point(module_scope)
