# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: com/baboea/qualifier.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x63om/baboea/qualifier.proto\x12\ncom.baboea\"\x12\n\x03Ids\x12\x0b\n\x03ids\x18\x01 \x03(\t\"t\n\tQualifier\x12\"\n\x05query\x18\x01 \x01(\x0e\x32\x11.com.baboea.QueryH\x00\x12\x0c\n\x02id\x18\x02 \x01(\tH\x00\x12$\n\tselection\x18\x03 \x01(\x0b\x32\x0f.com.baboea.IdsH\x00\x42\x0f\n\rqualifierType*\x10\n\x05Query\x12\x07\n\x03\x41LL\x10\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.baboea.qualifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERY']._serialized_start=180
  _globals['_QUERY']._serialized_end=196
  _globals['_IDS']._serialized_start=42
  _globals['_IDS']._serialized_end=60
  _globals['_QUALIFIER']._serialized_start=62
  _globals['_QUALIFIER']._serialized_end=178
# @@protoc_insertion_point(module_scope)
